# Official Supabase MCP server via npx
[mcp_servers.supabase]
command = "npx"
args = [
  "-y",
  "@supabase/mcp-server-supabase@latest",
  "--project-ref=ivsjnytypbxblnsuuaxd"
]

# Pass the access token directly. Other SUPABASE_* vars are inherited from the parent env
# when launching Codex via `./codex.makalah` (which exports .env values).
env = { SUPABASE_ACCESS_TOKEN = "sbp_c253f3e596a617e905e0f91133aa1e7ad6556558" }
